// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFAQc-1D0tfuNwWpOJje-XXP2hy_Xfxxk',
    appId: '1:876197887143:web:01b49a51cd63ee703e2f82',
    messagingSenderId: '876197887143',
    projectId: 'memoapp-85d8f',
    storageBucket: 'memoapp-85d8f.firebasestorage.app',
    authDomain: 'memoapp-85d8f.firebaseapp.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFAQc-1D0tfuNwWpOJje-XXP2hy_Xfxxk',
    appId: '1:876197887143:android:01b49a51cd63ee703e2f82',
    messagingSenderId: '876197887143',
    projectId: 'memoapp-85d8f',
    storageBucket: 'memoapp-85d8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3qvsnvFIytZcQN8DlA6LeO4oUodAQEcg',
    appId: '1:876197887143:ios:12366e2f0e9a38ad3e2f82',
    messagingSenderId: '876197887143',
    projectId: 'memoapp-85d8f',
    storageBucket: 'memoapp-85d8f.firebasestorage.app',
    iosClientId:
        '876197887143-m99e5fh7iu75as1vqkcajl0a3rnpgt80.apps.googleusercontent.com',
    iosBundleId: 'com.giwoo.memoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3qvsnvFIytZcQN8DlA6LeO4oUodAQEcg',
    appId: '1:876197887143:ios:12366e2f0e9a38ad3e2f82',
    messagingSenderId: '876197887143',
    projectId: 'memoapp-85d8f',
    storageBucket: 'memoapp-85d8f.firebasestorage.app',
    iosClientId:
        '876197887143-m99e5fh7iu75as1vqkcajl0a3rnpgt80.apps.googleusercontent.com',
    iosBundleId: 'com.giwoo.memoapp',
  );
}
